### PR TITLE
removed gap as primary

### LINKED ISSUE #48: Extended spacing systems with fallback
Proposal to change spacing classes to a singular class `.marX` with modifier `isSpace` allowing for a more memorable spacing utility. Early explorations ran into limitations with destructiveness in children which required swapping css variables & resetting children.

```
:root {
  --gap-1: 2rem;
  --gap-2: 4rem;
}

.isSpace {
  --space-1: 4rem;
  --space-2: 6rem;
}

.isSpace * {
  --space-1: initial;
  --space-2: initial;
}

.mar1 {
  margin: var(--space-1, var(--gap-1));
}

.mar2 {
  margin: var(--space-2, var(--gap-2));
}
```

### PR DESCRIPTION
**Pull request by atav1k**
fixed component `--gap` to close #48

### CODE REVIEW

**Comment by atav1k** [comment]
Checked it locally with the blog, no issues except I don't know where you used gap spacing

**Comment by chasestarr** [comment]
let me know when you publish and will update the blog

**Comment by chasestarr** [comment]
may want to publish as a `major` release. blog will pick up any patch releases automatically

**Comment by atav1k** [comment]
Give me till these landing pages ship, then we'll go major? For now I'm feeling a feature freeze though.

**Pull request merged**
